- sintr_worker/bin/startup.dart
- sintr_worker/bin/worker_isolate.dart
> Migrate work task into an isolate

- sintr_common/lib/storage_comms.dart
- sintr_worker/bin/startup.dart
Add the response mechanism so the controller can read the data back again.
TBR @danrubel
> Store the results of the computation in datastore

- sintr_common/lib/logging_utils.dart
- sintr_worker/bin/startup.dart
> Factor logging setup into a support library

- sintr_common/lib/auth.dart
- sintr_common/lib/logging_utils.dart
TBR @danrubel 
Very minor refactoring to move the use of logging to the support library.
> Use logging_utils for logging in auth

- tools/scripts/deploy_image.sh
- tools/scripts/deploy_worker_cluster.sh
- tools/scripts/upload_sample_src.sh
TBR @danrubel 
Control scripts for the worker nodes
These will need to be parameterized for different projects before production use.
> Worker control scripts

- sintr_analysis_server_example/bin/create_tasks.dart
- sintr_analysis_server_example/bin/reset.dart
- sintr_analysis_server_example/lib/instrumentation_lib.dart
- sintr_analysis_server_example/pubspec.yaml
- sintr_analysis_server_example/test_driver.dart
- sintr_analysis_server_example/worker_isolate.dart
- sintr_common/bin/uploadSource.dart
- sintr_common/lib/logging_utils.dart
- sintr_common/lib/task_utils.dart
- sintr_common/lib/tasks.dart
- sintr_common/pubspec.yaml
- sintr_worker/bin/startup.dart
- sintr_working/pubspec.yaml
- tools/scripts/run_local_worker.sh
- tools/scripts/worker_startup.sh
@danrubel TBR
This is still at the experiment stage. It's a first test of the distributed architecture running analysis server logs processing. I'm currently running it on a 4k sessions data set.
Once we've ironed out the issues in the infrastructure I'll clarify the design of what lives where and harden. E.g. the configuration state of e.g. the task queues is littered throughout the code at the moment.
> Test extracting high priority log events

- sintr_analysis_server_example/bin/create_tasks.dart
- sintr_analysis_server_example/bin/query.dart
- sintr_analysis_server_example/bin/reset.dart
- sintr_analysis_server_example/worker_isolate.dart
- sintr_common/lib/tasks.dart
- tools/scripts/deploy_worker_cluster.sh
- tools/scripts/destroy_cluster.sh
@danrubel TBR
More tools and tweaks that I'm needing to continue the experiments.
> Minor cleanup + cluster shutdown tool

- sintr_analysis_server_example/bin/create_tasks.dart
- sintr_analysis_server_example/bin/reset.dart
- sintr_analysis_server_example/lib/instrumentation_lib.dart
- sintr_common/lib/task_utils.dart
- sintr_common/lib/tasks.dart
TBR @danrubel 
Parameterise the block sizes and extract the argument names
> Adjust block sizes and extract arg names

- sintr_analysis_server_example/lib/completion_metrics.dart
- sintr_analysis_server_example/test_driver.dart
@lukechurch 
- first cut completion metrics extractor/reducer
- enhanced test_driver to exercise reducer
> first cut completion metrics extractor/reducer

- sintr_analysis_server_example/lib/session_info.dart
- sintr_analysis_server_example/test/session_info_test.dart
- sintr_analysis_server_example/test_driver.dart
@lukechurch 
- extract session info and count sessions on SDKs for each day
- update test_driver to extract session info from associated PRI file
- fix test driver to process last message(s)
The test_driver in this PR supersedes the test_driver in https://github.com/lukechurch/sintr/pull/39
This is a step towards addressing https://github.com/lukechurch/sintr/issues/37
> extract session info and count sessions on SDKs for each day

- .gitignore
- sintr_analysis_server_example/lib/completion_metrics.dart
- sintr_analysis_server_example/lib/instrumentation_lib.dart
- sintr_analysis_server_example/test_driver.dart
@lukechurch 
- update completion metrics to split results by sdk version
- update test_driver to extract session info from associated PRI file
- fix test driver to process last message(s)
> update completion metrics to split results by sdk version

- sintr_analysis_server_example/lib/instrumentation_lib.dart
- sintr_analysis_server_example/lib/instrumentation_processor.dart
- sintr_analysis_server_example/lib/session_info.dart
- sintr_analysis_server_example/lib/session_metrics.dart
- sintr_analysis_server_example/test_driver.dart
@lukechurch PTAL Not complete, but steps towards removing session metadata knowledge from test_driver
> extract session metadata processing into session_info (WIP)

- sintr_analysis_server_example/lib/completion_metrics.dart
- sintr_analysis_server_example/lib/instrumentation_transformer.dart
- sintr_analysis_server_example/lib/session_info.dart
- sintr_analysis_server_example/lib/session_metrics.dart
- sintr_analysis_server_example/test/session_metrics_test.dart
- sintr_analysis_server_example/test_driver.dart
@lukechurch 
- update test_driver to use new LogItemTransformer
- extract session info constants
If this change looks good, then the next step is to update worker_isolate.dart to use LogItemTransformer and delete instrumentation_processor.dart
> update test_driver to use new LogItemTransformer

- sintr_analysis_server_example/lib/query/versions.dart
- sintr_analysis_server_example/worker_isolate.dart
@danrubel Update the worker_isolate to use a map object. Add a version mapper.
> Update worker_isolate to use objects

- sintr_analysis_server_example/lib/query.dart
- sintr_analysis_server_example/lib/query/completion_metrics.dart
- sintr_analysis_server_example/test/query/completion_metrics_test.dart
- sintr_analysis_server_example/test_driver.dart
@lukechurch 
- add Mapper#addResult function to collect extraction results
- revise reducer function to accept key, value, result
- calculate 90th and 99th % completion times
> Mapper#addResult function and calculate 90th and 99th % completion times

- sintr_analysis_server_example/lib/query/versions.dart
- sintr_analysis_server_example/worker_isolate.dart
- sintr_common/lib/tasks.dart
- sintr_working/worker_isolate.dart
TBR @danrubel 
These are fairly minor update tweaks.
> Minor fixes and a counting reducer for versions

- sintr_analysis_server_example/lib/query/versions.dart
- sintr_analysis_server_example/lib/session_info.dart
- sintr_analysis_server_example/worker_isolate.dart
@danrubel Just as an FYI so you don't repeat the work
This isn't the final place where this code should live
> WIP: SDK version info for completions

- sintr_analysis_server_example/lib/instrumentation_query.dart
- sintr_analysis_server_example/lib/query.dart
- sintr_analysis_server_example/lib/query/completion_metrics.dart
- sintr_analysis_server_example/lib/query/session_ldap.dart
- sintr_analysis_server_example/test/query/all.dart
- sintr_analysis_server_example/test/query/completion_metrics_test.dart
- sintr_analysis_server_example/test/query/session_ldap_test.dart
- sintr_analysis_server_example/test_driver.dart
@lukechurch 
- first cut session ldap query
- extract InstrumentationMapper
- update test_drive to process all files in a directory
- pull up orderedInsert function from completion_metrics to instrumentation_query
- pull up isMapComplete into Mapper and update test_driver
> first cut session ldap query

- sintr_analysis_server_example/lib/instrumentation_transformer.dart
@lukechurch There are some types of queries that might still be valid even if some message blocks are missing. With this change, the transformer can be configured to allow non-sequential blocks, but defaults to not allow them.
> optionally allow non-sequential messages

- sintr_analysis_server_example/bin/decompress.dart
> new decompress log utility

- sintr_analysis_server_example/lib/query/severe_log.dart
> first cut severe log query

- sintr_analysis_server_example/lib/query/severe_log.dart
@lukechurch as discussed, revised severe log query to produce
date -> sdkVersion -> session id -> # severe log entries
> revise severe log query

- sintr_analysis_server_example/lib/instrumentation_query.dart
- sintr_analysis_server_example/test_driver.dart
- sintr_analysis_server_example/worker_isolate.dart
> stop extraction after first 1B log entries have been processed

- sintr_analysis_server_example/lib/query/versions.dart
> Update version map to use addResult rather than return

- sintr_analysis_server_example/worker_isolate.dart
> Report whether mapper was stopped

- sintr_analysis_server_example/bin/query.dart
TBR @danrubel Trivial configuration change adjusting the rate of polling
> Slower query loop

- tools/scripts/delete_cluster.sh
- tools/scripts/deploy_worker_cluster.sh
- tools/scripts/run.sh
Extract cluster size to a parameter
Upload driver scripts to target us-central
Use Standard disks instead of SSDs
@danrubel
> Update cluster configuration

- sintr_analysis_server_example/bin/create_tasks.dart
- sintr_analysis_server_example/bin/query.dart
- sintr_common/lib/gae_utils.dart
- sintr_common/lib/logging_utils.dart
- sintr_common/lib/task_utils.dart
- tools/scripts/delete_cluster.sh
- tools/scripts/deploy_worker_cluster.sh
- tools/scripts/run.sh
@danrubel Paged bucket listing is much faster and more reliable than the default implementation
> Better bucket listing

- sintr_analysis_server_example/test/md5_test.dart
> new md5 comparison test - dart vs openssl

- sintr_analysis_server_example/lib/bucket_util.dart
- sintr_analysis_server_example/test/bucket_util_test.dart
- sintr_analysis_server_example/test_driver.dart
- sintr_analysis_server_example/worker_isolate.dart
@lukechurch Here's my first cut. Unfortunately bucket_utils does not properly throttle the download to prevent memory overload. Will poke at it more tomorrow. Suggestions are most welcome.
> bucket utils for worker isolate

- sintr_analysis_server_example/lib/query/versions.dart
> Return date for versions

- sintr_common/lib/task_utils.dart
- sintr_common/lib/tasks.dart
Fix a git sync issue in task_utils
Add support for storing MD5 in the storage locations
TBR @danrubel
> Task config cleanup + MD5 caching

- sintr_analysis_server_example/worker_isolate.dart
@danrubel using Zones introduces some unexpected bugs. Revert to exception handling and letting the nodes crash and get restarted by the driver script
> Revent use of zones

- sintr_analysis_server_example/bin/delete_results.dart
- sintr_common/lib/gae_utils.dart
> Add tool: Delete results for a specific job

- sintr_analysis_server_example/bin/create_tasks.dart
- sintr_common/lib/task_utils.dart
- tools/scripts/run.sh
- Introduce the first part of job handling
- Add incremental job names, input filtering to create_tasks
@danrubel
> First part of Jobs

- sintr_common/lib/tasks.dart
> Slow ownership status request queries

- sintr_analysis_server_example/bin/query.dart
Implement @kevmoo's suggested improvement
> Const duration

- sintr_analysis_server_example/lib/bucket_util.dart
- sintr_analysis_server_example/lib/query/severe_log.dart
@danrubel PTAL
This reports the list of times up to a limit, after that it only reports any additional data as counts.
> Count severe log messages, cap number being reported

- sintr_analysis_server_example/bin/export_session.dart
@danrubel TBR: Add tool to export a session from the compressed file
> Export session from compressed file

- sintr_analysis_server_example/bin/bucket_status.dart
@danrubel TBR: Add a tool to list the number of items in each stage of the pipeline
> Bucket status tool

- tools/scripts/sync_datasets.sh
@danrubel TBR: Tool to sync the later stages of pipeline
> Sync buckets in the pipeline

- sintr_worker/bin/startup.dart
> Improve cache hit/miss reporting + refactor timing delay

- sintr_common/lib/tasks.dart
@danrubel This switches the objects bound to the datastore to use a staleness policy for a number of the objects, this should considerably reduce the datastore read traffic which is currently the cost dominator for the system.
> Add a policy for the backingstore being clean/stale

- sintr_analysis_server_example/bin/create_tasks.dart
- sintr_analysis_server_example/bin/query_wait_for_done.dart
- sintr_analysis_server_example/lib/job_config.dart
- sintr_analysis_server_example/lib/query/severe_log.dart
- sintr_analysis_server_example/lib/stacktrace_model.dart
- sintr_analysis_server_example/local_reducer_severe.dart
- sintr_analysis_server_example/local_reducer_versions.dart
- sintr_analysis_server_example/local_stacktrace_cluster.dart
- sintr_analysis_server_example/pubspec.yaml
- sintr_analysis_server_example/test_driver.dart
- sintr_analysis_server_example/test_reduce_driver.dart
- sintr_analysis_server_example/worker_isolate.dart
- sintr_common/bin/uploadSource.dart
- sintr_common/example/create_task_example.dart
- sintr_common/example/reset_tasks_example.dart
- sintr_common/lib/bucket_utils.dart
- sintr_common/lib/tasks.dart
- sintr_worker/bin/startup.dart
- sintr_worker/pubspec.yaml
- sintr_working/pubspec.yaml
- tools/scripts/run.sh
- tools/scripts/runExceptionCluster.sh
- tools/scripts/worker_startup.sh
@danrubel WIP for a local reducer for clustering, with a pre-filter for uniqueness.
> Stack trace cluster

- z_sintr_code_analysis_example/bin/create_tasks.dart
- z_sintr_code_analysis_example/bin/query_wait_for_done.dart
- z_sintr_code_analysis_example/lib/analyse_path.dart
- z_sintr_code_analysis_example/pubspec.yaml
- z_sintr_code_analysis_example/tools/run.sh
- z_sintr_code_analysis_example/tools/upload_src.sh
- z_sintr_code_analysis_example/worker_isolate.dart
@danrubel PTAL
This adds a project for doing distributed analysis on large corpuses of Dart files. This can serve as both a feature vector (state of code) and a way of doing 100x faster testing of the the analyzer.
> Add project for running Analysis on bulk data

- analysis_server_example/worker_isolate.dart
- sintr_worker/bin/startup.dart
- sintr_worker/watchdog.sh
- tools/scripts/deploy_worker_cluster.sh
Harden the configuration of executions
> Harden configuration

- analysis_server_example/local_reducer_severeCount.dart
> Add a reducer to produce severe error reports

- analysis_server_example/tools/batch_execute.sh
> Generate severe counts

- analysis_server_example/tools/batch_execute.sh
> Add directory creation and population
